### ISSUE TITLE
Reconstructed Movie is too thin. 

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#100]
Doesn't appear to have been made from the full volume. 
Possible just need to increase space from 000 to 0000?

{
  "LocalAlignments": 0,
  "THICKNESS": 1500,
  "TargetNumberOfBeads": 50,
  "TwoSurfaces": 0,
  "adoc_template": "cryo_brt",
  "callback_url": "https://hedwig2qa.niaid.nih.gov/api/pipeline/S9325",
  "fiducialless": 0,
  "file_name": null,
  "focus": 0,
  "gold": 10,
  "input_dir": "/RTB/efischer/hansenbry-2022-0112-NIAID-QA/TEM-Tomo-2022-0908-V2Testing/CryoTest3",
  "montage": 0,
  "token": "eyJ1c2VyIjp7ImlkIjowLCJmaXJzdE5hbWUiOiIiLCJsYXN0TmFtZSI6IiIsImFjY291bnQiOiIiLCJyb2xlSUQiOjAsInJvbGUiOm51bGx9sidiI6MSwicyI6IkxqamNtYm55akJkM0xJUi9EbmExMXgvUjdRV1Uvd2piMEVwOE5rb3ZcdTAwMkJBRT0ifX0=",
  "trackingMethod": 0
}

**Comment by NetaFG** [comment]
See an example of a too thin reconstructed movie in QA :
\\ai-fas12\RMLEMHedwigQA\Assets\RTB\efischer\hansenbry-2022-0112-NIAID-QA\TEM-Tomo-2022-0908-V2Testing\NovRTtomoTest\2013-1206-dA30_5-BSC-1-02_5

**Sample name: NovRTtomoTest**

See Hedwig UI:
https://hedwig2qa.niaid.nih.gov/sessions/U2Vzc2lvbjoyMjAw/samples
https://hedwig2qa.niaid.nih.gov/recmovie/UmVjb3JkOjE1OTg2Mw==

**Comment by philipmac** [comment]
recon seems to run OK on local machine, looks dark / grainy on HPC however.

**Comment by philipmac** [comment]
fixed in https://github.com/niaid/image_portal_workflows/pull/123
