### ISSUE TITLE
BRT pipeline should return the path to ..._ave.mrc in the `primaryFilePath` parameter.

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#108]
This came up during the live testing at RML. The EM team would like to enable users to download the _ave.mrc file for the BRT-type sessions.

Hence, the pipeline callback should include the path to:_ave.mrc file in the `primaryFilePath ' parameter.

**Comment by philipmac** [comment]
I'm not sure this is OK. I'll need to talk to Seva about this.

**Comment by philipmac** [comment]
Went over this with Seva. Probably not possible. 

If they want this _ave file, then I can add it to the callback, and they can download it. 

Basically the entire concept of downloading mrc files via the web interface seems silly however, given they have direct access to the filesystem and can dl files much much quicker via that interface. 

I'm not going to do anything here for now, as it will break things badly on the GUI.

**Comment by NetaFG** [comment]
Please see Seva's comment on ticket https://jira.niaid.nih.gov/browse/HEDWG2-627:

If the pipeline provides the desired path as the "primary file" in the callback, this will happen with no changes to the API

**Comment by philipmac** [comment]
I report the _ave.mrc file as the asset named `volume`. 

If the GUI wants to download that file, it's available for use. 

The input, the file/files that generate an output are listed as `PrimaryFilePath`. I write the outputs to an outputs directory called Assets. I list the items of interest as assets, linked with the primaryFilePath. 

If a browser wants to link to a file, that logic is done on the level of GUI, it doesn't change the logic of the callback or workflow.
