### ISSUE TITLE
BRT run error - 10/21/2022

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#109]
File system path: \\ai-fas12\RMLEMHedwigDev\Projects\RTB\darrellh\nguyenm8-2022-0920-test\TEM-Tomo-2022-0921-Neta_3D_Test\RT_Tomo

Time of the test around: 3:15 pm EST ( 21/10/2022)

Test details:
Navigate to :https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjoyNTAw/samples

Check the RT_tomo sample -> run pipeline -> BRT -> select the parameters as noted in ticket https://jira.niaid.nih.gov/browse/HEDWG2-531 (The samples files are a copy of the files that were tested by Bryan in QA - all default parameters excepts for the thickness which was set to 500)

and hit "Run"

The status of the run immediately changed to queued and then running.

Navigate to :https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjoyNTAw/samples

Check the RT_tomo-2 sample -> run pipeline -> BRT -> select the parameters as noted in ticket https://jira.niaid.nih.gov/browse/HEDWG2-531 (The samples files are a copy of the files that were tested by Bryan in QA - all default parameters excepts for the thickness which was set to 500)

and hit "Run"

The status of the run immediately changed to queued and then running.
After a few minutes, the sample status changed to "error" . The assets folder is empty (\\ai-fas12\RMLEMHedwigDev\Assets\RTB\darrellh\nguyenm8-2022-0920-test\TEM-Tomo-2022-0921-Neta_3D_Test\RT_Tomo)

See the Json
{
  "LocalAlignments": 1,
  "THICKNESS": 500,
  "TargetNumberOfBeads": 50,
  "TwoSurfaces": 1,
  "adoc_template": "plastic_brt",
  "callback_url":
"[https://goat.niaid.nih.gov/hedwig/api/pipeline/S10818/2"](https://goat.niaid.nih.gov/hedwig/api/pipeline/S10818/2%22),
  "fiducialless": 0,
  "file_name": null,
  "focus": 0,
  "gold": 10,
  "input_dir":
"/RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo",
  "montage": 0,
  "token":
"ddd",
  "trackingMethod": 0
}

* Please note that the above set of input parameters was verified again with Bryan.

**Comment by NetaFG** [comment]
Tested in Dev (11/3/2022)
Test = PASS

Pipeline run: 
http://44.192.88.156:8080/default/flow-run/a15b7ec9-eca3-4387-acda-c594fd74d497
All default parameters except for the thickness = 500
 Hedwig UI:
https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjoyNTAw/samples
File path:
 \\ai-fas12\RMLEMHedwigDev\Projects\RTB\darrellh\nguyenm8-2022-0920-test\TEM-Tomo-2022-0921-Neta_3D_Test\RT_Tomo-2

**Comment by philipmac** [comment]
@NetaFG  - fix should be deployed in dev

tested http://44.192.88.156:8080/default/flow-run/529b3374-fa8d-46b6-86ac-25bcd2576dca
with 
```

 {
  "LocalAlignments": 1,
  "THICKNESS": 500,
  "TargetNumberOfBeads": 50,
  "TwoSurfaces": 1,
  "adoc_template": "plastic_brt",
  "callback_url": "https://goat.niaid.nih.gov/hedwig/api/pipeline/S10819/2",
  "fiducialless": 0,
  "file_name": null,
  "focus": 0,
  "gold": 10,
  "input_dir": "/RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2",
  "montage": 0,
  "token": "ss==",
  "trackingMethod": 0
} 
```

**Comment by philipmac** [comment]
{`"files": [{"primaryFilePath": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20131030-dA30-5-RK13_4.mrc", "title": "20131030-dA30-5-RK13_4", "assets": [{"type": "thumbnail", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20131030-dA30-5-RK13_4/keyimg_20131030-dA30-5-RK13_4_s.jpg"}, {"type": "keyImage", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20131030-dA30-5-RK13_4/20131030-dA30-5-RK13_4_ali.065.jpg"}, {"type": "neuroglancerPrecomputed", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20131030-dA30-5-RK13_4/neuro-20131030-dA30-5-RK13_4", "metadata": {"neuroglancerPrecomputedMin": "41", "neuroglancerPrecomputedMax": "218", "neuroglancerPrecomputedFloor": "0", "neuroglancerPrecomputedLimit": "255"}}, {"type": "averagedVolume", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20131030-dA30-5-RK13_4/20131030-dA30-5-RK13_4_ave.mrc"}, {"type": "volume", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20131030-dA30-5-RK13_4/avebin8_20131030-dA30-5-RK13_4.mrc"}, {"type": "recMovie", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20131030-dA30-5-RK13_4/20131030-dA30-5-RK13_4_keyMov.mp4"}, {"type": "tiltMovie", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20131030-dA30-5-RK13_4/tiltMov_20131030-dA30-5-RK13_4.mp4"}]}, {"primaryFilePath": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20130412-Vn-poxtomo_8.st", "title": "20130412-Vn-poxtomo_8", "assets": [{"type": "thumbnail", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20130412-Vn-poxtomo_8/keyimg_20130412-Vn-poxtomo_8_s.jpg"}, {"type": "keyImage", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20130412-Vn-poxtomo_8/20130412-Vn-poxtomo_8_ali.065.jpg"}, {"type": "neuroglancerPrecomputed", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20130412-Vn-poxtomo_8/neuro-20130412-Vn-poxtomo_8", "metadata": {"neuroglancerPrecomputedMin": "146", "neuroglancerPrecomputedMax": "181", "neuroglancerPrecomputedFloor": "0", "neuroglancerPrecomputedLimit": "255"}}, {"type": "averagedVolume", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20130412-Vn-poxtomo_8/20130412-Vn-poxtomo_8_ave.mrc"}, {"type": "volume", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20130412-Vn-poxtomo_8/avebin8_20130412-Vn-poxtomo_8.mrc"}, {"type": "recMovie", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20130412-Vn-poxtomo_8/20130412-Vn-poxtomo_8_keyMov.mp4"}]}]}`


see: `{"type": "tiltMovie", "path": "RTB/darrellh/nguyenm8-2022-0920-test/TEM-Tomo-2022-0921-Neta_3D_Test/RT_Tomo-2/20131030-dA30-5-RK13_4/tiltMov_20131030-dA30-5-RK13_4.mp4"}` etc. Seems ok.

**Comment by NetaFG** [comment]
Test again on 11/7/2022
http://44.192.88.156:8080/default/flow-run/1757e3ae-4587-4164-b985-e0752e35634a
The Tilt movie does not show in QA

**Comment by NetaFG** [comment]
Tested on 11/8/2022
Test = PASS
See:
 https://hedwig2qa.niaid.nih.gov/sessions/U2Vzc2lvbjoyMjAw/samples
https://hedwig2qa.niaid.nih.gov/tiltmovie/UmVjb3JkOjE1OTg2Mw==
