### ISSUE TITLE
DM4 sample run error - 10/25/2022

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#110]
File path :
 \\ai-fas12\RMLEMHedwigDev\Projects\RTB\darrellh\nguyenm8-2022-0920-test\SEM-2022-0922-Neta_2D_Test\DM4_sample

test details:
Navigate to : https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjoyNTA2/samples
Check sample: DM4_sample
hit Run pipeline
check the "2D" pipeline-> run
The sample status changed from "Queued -> Running -> Error
{
    "data": [
        {
            "sampleId": 10829,
            "result": "Success",
            "runId": "88d1ad1a-f085-42c3-bcaa-ba40b5809514",
            "message": "{\"data\":{\"create_flow_run\":{\"id\":\"88d1ad1a-f085-42c3-bcaa-ba40b5809514\"}}}\n"
        }
    ]

{
    "data": [
        {
            "id": 10829,
            "title": "DM4_sample",
            "topSampleFileId": 0,
            "recordCount": 0,
            "parentExperiment": 3554,
            "parentSession": 2506,
            "parentProject": 1318,
            "pipelineStatus": "Queued",
            "hasUnapprovedSampleFiles": false
        },
       {
   {
    "data": [
        {
            "id": 10829,
            "title": "DM4_sample",
            "topSampleFileId": 0,
            "recordCount": 0,
            "parentExperiment": 3554,
            "parentSession": 2506,
            "parentProject": 1318,
            "pipelineStatus": "Error",
            "hasUnapprovedSampleFiles": false
        },

**Comment by philipmac** [comment]
http://44.192.88.156:8080/default/flow-run/88d1ad1a-f085-42c3-bcaa-ba40b5809514?logs

inputs: 
{
  "callback_url": "https://goat.niaid.nih.gov/hedwig/api/pipeline/S10829/1",
  "file_name": null,
  "input_dir": "/RTB/darrellh/nguyenm8-2022-0920-test/SEM-2022-0922-Neta_2D_Test/DM4_sample",
  "token": "ttt"
}

'/opt/rml/imod/bin/dm2mrc', '/mnt/ai-fas12/RMLEMHedwigDev/Projects/RTB/darrellh/nguyenm8-2022-0920-test/SEM-2022-0922-Neta_2D_Test/DM4_sample/20210525_1416.dm4', PosixPath('/gs1/Scratch/macmenaminpe_scratch/tmp9hdzh_0c/20210525_1416.mrc') returned non-zero exit status 1.

**Comment by NetaFG** [comment]
Tested this sample again.
1)https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjoyNTA2/samples
2) run pipeline -> 2D->run
3) The status of the sample changed from queued->running and then the sample card was created
4) The assets can be viewed at : https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjoyNTA2/samples
File path:
\\ai-fas12\RMLEMHedwigDev\Assets\RTB\darrellh\nguyenm8-2022-0920-test\SEM-2022-0922-Neta_2D_Test\DM4_sample
Test = PASS

**Comment by NetaFG** [comment]
### QA testing with Bryan (11/1/2022)
**The  Re-run workflow pipeline completed successfully but the DM4 images were still very dark.**
 Pipeline run: 
http://44.192.88.156:8080/default/flow-run/4ee3cf81-884c-42d9-af0b-8de2394ac64e
Raw Data:
\\ai-fas12\RMLEMHedwigQA\Projects\RTB\efischer\hansenbry-2022-0112-NIAID-QA\TEM-Tomo-2022-0908-V2Testing\2DTestNeta 
Hedwig UI:
https://hedwig2qa.niaid.nih.gov/sessions/U2Vzc2lvbjoyMjAw/samples

**However, a new sample pipeline run ( (a sample that had the "never" status) as if completed successfully but, the sample card is empty of records.**
Pipeline run:
http://44.192.88.156:8080/default/flow-run/d15e9313-d4d4-4fe1-a11c-e385d525672b

The raw data:
 \\ai-fas12\RMLEMHedwigQA\Projects\RTB\efischer\hansenbry-2022-0112-NIAID-QA\TEM-Tomo-2022-0908-V2Testing\dm4Test

The assets folder: ( contains only the .mrc file and none of the other expected assets such as the large and small thumbnails)
\\ai-fas12\RMLEMHedwigQA\Assets\RTB\efischer\hansenbry-2022-0112-NIAID-QA\TEM-Tomo-2022-0908-V2Testing\dm4Test\20210525_1013_A004_G000\work_dir_11_16AM_November_01_2022\20210525_1013_A004_G000

**Comment by NetaFG** [comment]
The lasted code version was promoted to QA and re-tested. The test completed successfully (all 128 records were created in the card).
