### ISSUE TITLE
FIB SEM run error - 11/3/2022

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#111]
Pipeline run: http://44.192.88.156:8080/default/flow-run/156ae765-3a93-40e5-bf92-d6d2185441c1
The pipeline failed at the last stage -> "copy work_dir" 
A card was created. Both the thumbnails and the Neuroglancer assets are there too, but the Neuroglancer does not look right.
 
See Hedwig UI:
https://hedwig2qa.niaid.nih.gov/neuroglancer/UmVjb3JkOjE1OTg1NA== ( Neuroglancer asset)
https://hedwig2qa.niaid.nih.gov/samples ( Large Thumbnail)

File Path:
\\ai-fas12\RMLEMHedwigQA\Projects\RTB\efischer\hansenbry-2022-0112-NIAID-QA\SEM-Tomo-2022-0112-JanTest\Test1
\\ai-fas12\RMLEMHedwigQA\Assets\RTB\efischer\hansenbry-2022-0112-NIAID-QA\SEM-Tomo-2022-0112-JanTest\Test1\set 1

**Comment by philipmac** [comment]
This is a no space left on device error. Closing.
