### ISSUE TITLE
FIB SEM pipeline should return the " corrected.mrc"  for the download operation

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#114]
Following the meeting Bryan H. on 11/4/2022
It was agreed that the "corrected.mrc" file is the file that the EM team would like to enable the users for the "download" operation. on UI side.

**Comment by NetaFG** [comment]
See Seva's comment on ticket : https://jira.niaid.nih.gov/browse/HEDWG2-628
It's the pipeline's responsibility to feed the desired file path to the API as the "primary file" parameter in the callback.

**Comment by philipmac** [comment]
Will add new asset, `correctedMRC`

see:  https://github.com/niaid/hedwig-comm-specs/issues/3

**Comment by philipmac** [comment]
deployed in dev - available for testing.

**Comment by sevaa** [comment]
Asset types is a closed list. Without a change in the API, new asset types won't be magically supported if the pipeline starts emitting them.

For now, I'll go ahead and add `correctedMRC` to the list, but going forward, please a bit more formal process on this one.

**Comment by philipmac** [comment]
Looking over the BRT workflow, the correct MRC file is passed as asset named `volume`

I can use this Asset type in FIBSEM too if we like. 
There's already dups in the Asset names, eg sometimes the thumbnail is called `thumnail` and sometimes `keyThumbnail`. 
I'd be OK with doing that simplification too.

**Comment by sevaa** [comment]
From what I've seen, the ..._ave.mrc is passed as `averagedVolume`. `volume` is the "avebin8" one, the binned file for Volslicer.

**Comment by philipmac** [comment]
Ah, yes. OK, `averagedVolume` is the base_ave.mrc. 

ok, I can use `correctedMRC` for now. If you'd like to use `averagedVolume` for consistency LMK. (And thumbs). 
Not a priority.

**Comment by sevaa** [comment]
I'd like you to run the changes to the externally visible interface by me first, specifically the stuff of https://github.com/niaid/hedwig-comm-specs/issues/4 and https://github.com/niaid/hedwig-comm-specs/issues/3 . Would that be possible?

**Comment by philipmac** [comment]
I use dev to do dev stuff, and QA to actually test. Lots of what goes into dev is placeholder. 
There's no tech lead in this project. I labeled the asset as correctedMRC as a placeholder, in order to start the conversation. 
At the time there was still talk of writing outputs into input dirs, and changing the fundamental logic of the callback. 

I have zero issue with swapping out or in asset tags.

**Comment by sevaa** [comment]
Can you send back the corrected.mrc as `averagedVolume` for uniformity? There isn't another output of the FIBSEM pipeline that's provided under that asset code, is there?

**Comment by philipmac** [comment]
yup, no problem. 

How about doing the same thing for thumbnail? Just calling them all `thumbnail` regardless of which pipeline makes them?

**Comment by philipmac** [comment]
Sorry - other changes to FIBSEM, haven't heard of anything requested recently. Testing has not really happened very much yet, so it's possible. I'd like to say no to any more changes prior to first release though.

**Comment by sevaa** [comment]
You can emit them as `thumbnail`, the code will take that. The old records, though, still have to be supported, so I can't phase out `keyThumbnail` altogether anyway.

**Comment by philipmac** [comment]
above updates deployed to dev

**Comment by NetaFG** [comment]
Tested on 11/22/2022
The test failed.
See JIRA Ticket:  https://jira.niaid.nih.gov/browse/HEDWG2-666

**Comment by philipmac** [comment]
I'm assuming: http://44.192.88.156:8080/default/flow-run/02f6637d-9b08-41d1-8aa0-f960c5a291d3?logs is the flow in question. 
Please elaborate from my perspective. Note, my perspective is related only to the: workflow, and the callback. It is not related to the GUI. 

{"files": [{"primaryFilePath": "RTB/darrellh/filipgranitn2-2022-0804-TestKeyword/SEM-Tomo-2022-0809-K_8_9_2022/YFV-Asibi/YFV-Asibi", "title": "YFV-Asibi", "assets": [{"type": "thumbnail", "path": "RTB/darrellh/filipgranitn2-2022-0804-TestKeyword/SEM-Tomo-2022-0809-K_8_9_2022/YFV-Asibi/YFV-Asibi/keyimg_sm.jpg"}, {"type": "keyImage", "path": "RTB/darrellh/filipgranitn2-2022-0804-TestKeyword/SEM-Tomo-2022-0809-K_8_9_2022/YFV-Asibi/YFV-Asibi/keyimg.jpg"}, {"type": "neuroglancerPrecomputed", "path": "RTB/darrellh/filipgranitn2-2022-0804-TestKeyword/SEM-Tomo-2022-0809-K_8_9_2022/YFV-Asibi/YFV-Asibi/neuro-YFV-Asibi", "metadata": {"neuroglancerPrecomputedMin": "-62", "neuroglancerPrecomputedMax": "386", "neuroglancerPrecomputedFloor": "111", "neuroglancerPrecomputedLimit": "255"}}, {"type": "averagedVolume", "path": "RTB/darrellh/filipgranitn2-2022-0804-TestKeyword/SEM-Tomo-2022-0809-K_8_9_2022/YFV-Asibi/YFV-Asibi/corrected.mrc"}]}]}

The above is the callback, note that Asset averagedVolume points to corrected.mrc.
