### ISSUE TITLE
"Copy workdir" error on BRT runs - Bryan H. QA Testing

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#119]
Tested on 11/16/2022
Pipeline run: http://44.192.88.156:8080/default/flow-run/442c7d55-d95a-443b-82ef-7a930a0b86aa

error message: 
Error during execution of task: AttributeError("'NoneType' object has no attribute 'copy_workdir_to_assets'")

These error repeated itself also for:
Pipeline run: http://44.192.88.156:8080/default/flow-run/b69f0f95-1d84-4096-a8ea-c77e084d4b36

**Comment by philipmac** [comment]
from Pipeline run: http://44.192.88.156:8080/default/flow-run/442c7d55-d95a-443b-82ef-7a930a0b86aa 

Errno 28] No space left on device: '/mnt/ai-fas12/RMLEMHedwigQA/Assets/RTB/efischer/hansenbry-2022-1116-HedwigV2/TEM-Tomo-2022-1116-3D-Data/SARS-CoV2/24hr-B5-cell2-2a/work_dir_04_23PM_November_16_2022/24hr-B5-cell2-2a/24hr-B5-cell2-2a_ave033.mrc'")]


from 
http://44.192.88.156:8080/default/flow-run/b69f0f95-1d84-4096-a8ea-c77e084d4b36

"[Errno 28] No space left on device: '/mnt/ai-fas12/RMLEMHedwigQA/Assets/RTB/efischer/hansenbry-2022-1116-HedwigV2/Cryo-TEM-Tomo-2022-1116-3D-Data/NMII/EF-NMII_2/work_dir_04_45PM_November_16_2022/EF-NMII_2/EF-NMII_2/neuro-EF-NMII_2/335pm/576-640_1280-1344_1344-1408.gz'"),

Running out of space on the device leaves me in a bad state, and I can't really code downstream of that. It's failing from that point, very badly, no matter what I do. 
I'm closing this issue as I can't control the disk
