### ISSUE TITLE
BRT pipeline assets are wrong - tested by Bryan 11/16/2022

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#120]
Samples reviewed :
\\ai-fas12\RMLEMHedwigQA\Assets\RTB\efischer\hansenbry-2022-1116-HedwigV2\Cryo-TEM-Tomo-2022-1116-3D-Data

\\ai-fas12\RMLEMHedwigQA\Assets\RTB\efischer\hansenbry-2022-1116-HedwigV2\TEM-Tomo-2022-1116-3D-Data

Pipeline runs of the above samples:
http://44.192.88.156:8080/default/flow-run/b69f0f95-1d84-4096-a8ea-c77e084d4b36
http://44.192.88.156:8080/default/flow-run/442c7d55-d95a-443b-82ef-7a930a0b86aa
http://44.192.88.156:8080/default/flow-run/e68fe4ca-666e-4753-afbf-0f8af6c27232
http://44.192.88.156:8080/default/flow-run/95bdeb64-88e8-438e-862c-f2b2ee12d0e2

See Bryan H. feedback:
Images in the movies are out of order for the tilt movie, rec movie seems to be a combo of out of order and not thick enough. the rec movies also aren't the correct thickness for what was given and seem to be out of order as well

**Comment by NetaFG** [comment]
A single file from the NMI and SARsCov2 samples will be tested in Dev.

**Comment by NetaFG** [comment]
Tested again:
Test 1:
Rerun NM_B in Dev
Pipeline run : http://44.192.88.156:8080/default/flow-run/91f05205-17fe-4a92-8328-44353c5345e6

Test 2:
Rerun SARsCov2_B
Pipeline run: http://44.192.88.156:8080/default/flow-run/4b73a453-4e50-44d2-8887-3e71c4b10900

Both runs successfully completed, and the assets VolSlicer and Reconstructed Movie were correct.
Hedwig UI:
https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjoyNTE1/samples
https://goat.niaid.nih.gov:7333/volslicer/UmVjb3JkOjE3NDE5Mg==
https://goat.niaid.nih.gov:7333/recmovie/UmVjb3JkOjE3NDE5Mg==
https://goat.niaid.nih.gov:7333/tiltmovie/UmVjb3JkOjE3NDE5Mg==

See Hansen , Bryan, Feedback:
The reconstructed movie is correct now. VolSlicer looks correct now too

@philipmac Please add details on the fix.

**Comment by NetaFG** [comment]
Once deployed to QA the EM team will repeat the test with additional files per sample.

**Comment by philipmac** [comment]
fixed in https://github.com/niaid/image_portal_workflows/tree/fix_recon_movie
