### ISSUE TITLE
Volslicer asset is too Thin

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#122]
Hedwig UI:
https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjoyNTE1/samples
Sample name: SARsCov2_B

Pipeline run:
http://44.192.88.156:8080/default/flow-run/25ce4b87-b686-4f1b-a371-15554a41fb58

File Path:
\\ai-fas12\RMLEMHedwigDev\Assets\RTB\darrellh\filipgranitn2-2022-1117-BRT_Testing\Cryo-TEM-Tomo-2022-1117-Nov_BRT_testing\SARsCov2_B\SARsCoV2_1

Review by Bryan on 11/17/2022
VolSlicer volume  looks too thin, doesn't look like even binned down that it's the thickness that you supplied (800)

**Comment by NetaFG** [comment]
Tested after the fix:

Rerun SARsCov2_B
Pipeline run: http://44.192.88.156:8080/default/flow-run/4b73a453-4e50-44d2-8887-3e71c4b10900

Both runs successfully completed, and the assets VolSlicer and Reconstructed Movie were correct.
Hedwig UI:
https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjoyNTE1/samples
https://goat.niaid.nih.gov:7333/volslicer/UmVjb3JkOjE3NDE5Mg==
https://goat.niaid.nih.gov:7333/recmovie/UmVjb3JkOjE3NDE5Mg==
https://goat.niaid.nih.gov:7333/tiltmovie/UmVjb3JkOjE3NDE5Mg==

See Hansen , Bryan, Feedback:
The reconstructed movie is correct now. VolSlicer looks correct now too
The issue is fixed

**Comment by philipmac** [comment]
fixed in https://github.com/niaid/image_portal_workflows/tree/fix_recon_movie
