### ISSUE TITLE
The partial failure/success workflow does not work as expected

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#124]
Tested on 11/23/2022
Navigate to https://hedwig2qa.niaid.nih.gov/sessions/U2Vzc2lvbjoyMjM4/samples
run the BRT pipeline for the sample: name "FailureTest"

 Pipeline run:
 http://44.192.88.156:8080/default/flow-run/886ca378-ed87-4f2b-ab90-d1498a90e539
File path:
\\ai-fas12\RMLEMHedwigQA\Assets\RTB\efischer\hansenbry-2022-1116-HedwigV2\TEM-Tomo-2022-1116-3D-Data\FailureTest\

The overall status is marked as "success"
A card is created but the it shows 0 Records instead of showing 2 records. Meaning, the records that passed successfully are not available on the UI
Please note that on the file system there were 2 records that had all assets ( GZH002, GZH004) and one failed (GZH003)

**Comment by philipmac** [comment]
Should be addressed in QA

See; http://44.192.88.156:8080/default/flow-run/2b3dd916-a972-4899-80f6-ee99bfbb7b0f?logs
