### ISSUE TITLE
The BRT pipeline takes significantly longer than anticipated to finish.

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#128]
This was reported by Bryan:

"These tomo runs are taking a really long time
1hr 45min for a single cryoTomo file so far
1hr 36min for a 500 slice thickness for rt tomo"
This is significantly longer than expected
fib-sem is running at the speed I would expect. tomo is almost unusably slow. We could get by, but will result in significant delay in getting people their data

See the latest's jobs from QA. 
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/f7d70638-9b3f-4eed-865d-8e068f200c95 (almost 4 hours)
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/15ff20b8-6dfd-4182-8a39-42ea8730076e ( 3 hours and 20 min)
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/d50258c3-81b0-448e-94c5-fe59f87c5452 ( almost 2 hours)

**Comment by NetaFG** [comment]
Please see Hediwg's 1 Wiki:
https://github.com/niaid/hedwig-api/wiki/TomoJS-3D-pipeline#neuroglancer-pyramid-generation

Neuroglancer pyramid generation
For the BRT pipeline, this step uses BASENAME_full_rec.mrc as the source, for the SEM-Tomo, it uses BASENAME.mrc

The pipeline converts the source file to the NIFTI 1 format into a file called nifti.nii under {WORKDIR}. This is done in process, with no third party involved. During conversion, the pixel format is converted:

SInt16 -> UInt16 (conversion by adding 32768)
SInt8 -> UInt8 (adding 128)
UInt8 pixels are left intact *All other pixel formats in the MRC are not supported and the pipeline errors out on those. Compressed pixels are not supported, either.
The pipeline runs the script for making a pyramid out of a NIFTI file (in the mrc2ngpc container):

volume-to-precomputed-pyramid --downscaling-method=average --flat {WORKDIR}/nifti.nii {WORKDIR}/hedwig/neuro-BASENAME

That generates the folder neuro_BASENAME under hedwig,

The pipeline runs the pixel intensity hystogram calculator from the tomojs_pytools package by NIAID:

mrc_visual_min_max {WORKDIR}/nifti.nii --mad 5 --output-json {WORKDIR}/mrc2ngpc-output.json

The pipeline reads the generated JSON and extracts the min and max values from it. They are used during the writeback

**Comment by philipmac** [comment]
I have read the wiki, I'm asking for:

a log from the previous Hedwig, and look at the precise command that's being run, specifically for volume-to-precomputed-pyramid

I want to run the actual file that was run previously on HPC through the ng binary, with the arguments that ran so quickly.

**Comment by philipmac** [comment]
[SARsCoV2_1_tomojs.log](https://github.com/niaid/image_portal_workflows/files/10219105/SARsCoV2_1_tomojs.log)
Notice the size difference in this demo file, the above file is ~25 times the size. 
It is expected to run for considerably longer. 

We would need to run a comparative test, eg with file used in log.

**Comment by philipmac** [comment]
please take notice that Bryan is not required to test this, we can. We do not need meetings at this point in time to look at this issue out. We are dealing with it, if we require a meeting with Bryan we will let you know.

**Comment by NetaFG** [comment]
See ticket https://jira.niaid.nih.gov/browse/HEDWG2-688

**Comment by blowekamp** [comment]
Created PR to add compress level as option to neuroglancer-scripts: HumanBrainProject/neuroglancer-scripts#24

Using compression level 1 takes about 10 min, with nearly the same data output size as level 9 taking 168 min.

**Comment by NetaFG** [comment]
This is from Bryan - FYI
that'll be nice to optimize the NG file, but I think the main speed issue right now is pre NG file generation. It's the fact that the creation of the input file for the NG file is creating a file that is much much larger than it should be.
so then the NG file looks to take forever because then the NG file gets even larger.

**Comment by philipmac** [comment]
`runtime.AlignedStack.any.binByFactor = 1`

appears to be not the correct value here for the adoc template. 

Should be 
set to `8`. 


Also, `binvol binning` should be changed to compensate. 

see: https://github.com/niaid/image_portal_workflows/commit/1dfaa2dd2bc6b850d98f28a864b37b3839d2ff3d

**Comment by philipmac** [comment]
https://github.com/niaid/image_portal_workflows/pull/134
