### ISSUE TITLE
3D pipeline error from Dec 28th 2022

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#135]
This is a copy of Cindi's email:

Hey there,
 
I submitted some cryo-tilt-series for the 3D pipeline yesterday afternoon and so far, none are showing up on Hedwig. I see that it is still ‘running’. I submitted ~20 or so and the thickness was 1500 (if that matters).
 
Thanks,
Cindi

Hedwig UI: https://hedwig.niaid.nih.gov/sessions/U2Vzc2lvbjoyODIy/samples
Hedwig Pipeline run: https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/fcc1d791-1cd0-412d-a103-350581b75e15

**Comment by philipmac** [comment]
Pipeline works as expected - 

BRT hangs, possible HPC issue. Investigate why walltime argument seems to be being ignored? 

Possibly put timeout on BRT task? In general walltime should (and previously did) work however. 


jobqueue:
  slurm:
    name: dask-worker

    # Dask worker options
    cores: 8                # Total number of cores per job
    memory: "64 GB"                # Total amount of memory per job
    processes: 1                # Number of Python processes per job

    # interface: ens160           # Network interface to use like eth0 or ib0
    death-timeout: 120           # Number of seconds to wait if a worker can not find a scheduler
    local-directory: /gs1/home/macmenaminpe/tmp       # Location of fast local storage like /scratch or $TMPDIR
    job_extra_directives: ["--gres=gpu:1"]

    # SLURM resource manager options
    shebang: "#!/usr/bin/env bash"
    queue: gpu
    project: null
    walltime: '10:00:00' <-------- ???

**Comment by NetaFG** [comment]
The status of the job on the API side was changed by Seva through the backend from "running" to "error" status. This enabled Cindi to rerun the same sample again. See: https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/eb4119fd-9978-4f94-b26d-12bdd556c43c
After 1 hour and 7 minutes, the run was declared "successful" with 18 images passing and 4 failing. 
The images and work_dir can be found in:
 \\ai-fas12.niaid.nih.gov\RMLEMHedwigProd\Assets\LID\marcotrigianoj2\marcotrigianoj2-2022-0126-LDL\Cryo-TEM-Tomo-2022-1208-LDL-B4_refreeze

**Comment by philipmac** [comment]
There does not appear to be an issue with the pipeline. 
Leaving open for now however, to remind me to test how to deal with hung HPC jobs and / or ensure `walltime` is still working.

**Comment by philipmac** [comment]
closing - will do general work on dask / slurm
