### ISSUE TITLE
accept mrc files as 2d inputs

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#144]
Need to get a demo input mrc file @NetaFG

**Comment by philipmac** [comment]
unclear how test files, at `ai-rmlsbatch1.niaid.nih.gov:/mnt/ai-fas12/RMLEMHedwigQA/TestData/2DmrcFiles` are meant to be processed.
Attempted 
`mrc_visual_min_max HUA13_00000_Jan11_patch_aligned_doseweighted.mrc`
and
`mrc2tif -j -S -24,26 HUA13_00000_Jan11_patch_aligned_doseweighted.mrc t.jpg` etc. 

Images not appearing to be displaying anything useful.

**Comment by philipmac** [comment]
I did ask the person who wrote IMOD what he would suggest as a good starting place for this and got this response


Can you use trimvol with the -meansd option, matching the mean and SD for autocontrasting in 3dmod?  (I seem to recall it is 140, 50).
I see I never added a direct TIFF output option for trimvol (I remember someone wanted that once) but it is easily done with
env IMOD_OUTPUT_FORMAT=TIF trimvol -meansd 140,50 -mode 0 ....

**Comment by philipmac** [comment]
- Do we care about the intermediate tiff file? (We think no.)
- We're assuming that the jpeg res is same - 1024x1024
- What's going on with aspect ratio? Do we care? 
- We believe the tiff files generated for the sample were screen grabs of 3dmod, having loaded up the mrc file. Is this the case?

**Comment by hansenbry** [comment]
@philipmac I had to go into my github dashboard to see the notification, but it's possible the email notification was just lagging behind

**Comment by hansenbry** [comment]
@philipmac 

> * Do we care about the intermediate tiff file? (We think no.)
       - No we don't need any intermediate files just the original 
> * We're assuming that the jpeg res is same - 1024x1024
       - The raw inputs are going to be W 11,520 ✗ H 8,184 or W 5,760 ✗ H 4,092 for the most part
> * What's going on with aspect ratio? Do we care?
      - If we can try and keep the aspect ratio as we are for the other 2D items we process
> * We believe the tiff files generated for the sample were screen grabs of 3dmod, having loaded up the mrc file. Is this the case?
      - The tiff files were exported out of 3dmod so it was generated from a set of IMOD commands I'm just not sure which. I reached out to David Mastronarde to see what the commands were for these 32-bit real mrc files and he suggested the following

Can you use trimvol with the -meansd option, matching the mean and SD for autocontrasting in 3dmod?  (I seem to recall it is 140, 50).

I see I never added a direct TIFF output option for trimvol (I remember someone wanted that once) but it is easily done with

env IMOD_OUTPUT_FORMAT=TIF trimvol -meansd 140,50 -mode 0 ....

you then would use the trimvol to scale the histogram and then output a tif file

**Comment by blowekamp** [comment]
It is my understand the goal of this pipeline is to produce a JPEG image about 1kx1k. And a thumbnail too.

Directly performing antilaising/bandpass filtering from the original input to the target resolution then performing intensity scaling should result in the best quality image which preserved the original signal.

The following command should be able to archive this:
```
 env IMOD_OUTPUT_FORMAT=TIF newstack --shrink $shrink_factor$ -antialias 6 -mode 0 -meansd 140,50 HUA13_00014_Jan11_patch_aligned_doseweighted.mrc output.tif
```

Where `shrink_factor` is computed by the `number_number_of_pixel / target_number_of_pxiel` ( that is the minimum number of pixels in a x y dimension of the image ).

**Comment by blowekamp** [comment]
@hansenbry  Bellow in the produce tif ( converted to png for inclusion here). Is this what is expected?
![out](https://user-images.githubusercontent.com/321061/213767473-4435367c-4a7d-4319-93fc-6983dc010799.png)

**Comment by hansenbry** [comment]
> @hansenbry Bellow in the produce tif ( converted to png for inclusion here). Is this what is expected? ![out](https://user-images.githubusercontent.com/321061/213767473-4435367c-4a7d-4319-93fc-6983dc010799.png)


@philipmac Ya this looks correct. These cryo EM images aren't pretty and look like noise at times depending on how much protein is in the ice

**Comment by philipmac** [comment]
From @hansenbry 

(FYI @blowekamp )
Ran some 2D mrc files see https://hedwig2qa.niaid.nih.gov/sessions/U2Vzc2lvbjoyMjU2/samples 

Images look a little grainy to me almost if the histogram is collapsed a little too far and clipping into extremes.

**Comment by philipmac** [comment]
![CWD-F2_00011_Feb08_patch_aligned_doseweighted_LG](https://user-images.githubusercontent.com/1271929/218193995-a746be7a-cfdf-483a-9cb2-31edfe33815b.jpeg)
![CWD-F2_00000_Feb08_patch_aligned_doseweighted_LG](https://user-images.githubusercontent.com/1271929/218194005-ec38d96f-4ace-48d7-a445-4fd640a712ac.jpeg)

**Comment by blowekamp** [comment]
Here is the histogram of the first image.
![image](https://user-images.githubusercontent.com/321061/223746521-f65543c8-df42-4432-a01f-77a0ef34a635.png)

**Comment by philipmac** [comment]
test fixes deployed - @hansenbry will test in QA
