### ISSUE TITLE
General conversation regarding the processing of Light Microscopy inputs

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#147]
Need to evaluate a couple tools to do the conversion. 

- Get all LM image file formats and evaluate the tools once on all of them instead of each time a new file format is requested.

- a front end for viewer the LM images which supports the false coloring. 

Options include:  
- Neuroglancer may be able to do it with some configurations.
-  client side napari, 
- fiji configured to use zarr. 
- There may be components of OMERO which would be useful to us.
- https://github.com/imagej/pyimagej

**Comment by philipmac** [comment]
One type of image file will derive from Nanostring. (This will be priority for LM for now.)
Need an example of this.

**Comment by blowekamp** [comment]
The long standing tool for reading LM image files is OME [bioformats](https://www.openmicroscopy.org/bio-formats/) which primarily outputs [OME-TIFF files](https://docs.openmicroscopy.org/ome-model/5.6.3/ome-tiff/). Current work from OME is on [OME-NGFF ](https://ngff.openmicroscopy.org/latest/)( based on zarr).

There is also SCIFIO from the image community: https://scif.io

**Comment by philipmac** [comment]
Additionally there will be a CZI output. 
Can czi file be displayed natively within FIJI? or do we always want to convert them to some intermed format.

**Comment by blowekamp** [comment]
Will the Hedwig users be exposed to file format? Does it matter to them?
