### ISSUE TITLE
Investigate the failure of a 2D pipeline run from Jan 24, 2023

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#149]
This issue was reported by Bryan H. on January 24, 2023 as a part of ticket https://jira.niaid.nih.gov/browse/HEDWG2-714

"Also one of the 2D samples failed, but it's nothing but jpg files"

UI Path:

https://hedwig.niaid.nih.gov/sessions/U2Vzc2lvbjoyODQ1/samples

File path:

\\ai-fas12.niaid.nih.gov\RMLEMHedwigProd\Projects\LID\marcotrigianoj2\marcotrigianoj2-2023-0123-HCV-E1\Cryo-TEM-2023-0123-sfconE1-H114-4E3

Pipeline run

https://prefect1.hedwig-workflow-api.niaidprod.net/default/task-run/84348407-669d-47e8-b4bb-cde0d7941575?logs

**Comment by NetaFG** [comment]
This is the error message:
FileNotFoundError: [Errno 2] No such file or directory: '/gs1/Scratch/macmenaminpe_scratch/tmp89xqtu8w'

**Comment by philipmac** [comment]
Looks like a problem with the file system maybe?
Unclear. Ran workflow again, and directory appears to be there as expected.
