### ISSUE TITLE
Add bioformats2raw usage for HPC

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#172]
https://github.com/glencoesoftware/bioformats2raw can convert various formats to zarr outputs.

Usage (including HPC set up) should be added to docs. This can be added to : `docs/source/hpc.rst`

**Comment by blowekamp** [comment]
This is a Java based package, with a dependency a system libblosc library for compression. There are two primary ways bioformats2raw can be installed:

1. Directly from the package in the GitHub releases: https://github.com/glencoesoftware/bioformats2raw/releases This will require a system java and libblosc. The Python package "blosc"  can also provide this library if "LD_LIBRARY_PATH" is configured to the location of the library in the python packages.
2. The full stack can be installed via [Conda](https://github.com/ome/conda-bioformats2raw). This has the dependencies for java and libblosc. A Conda environment can be created without python, which may help keep stacks separate.

**Comment by blowekamp** [comment]
The management of the HPC setup outside of my area. Please let me know if you need more information about how to choose how the environment should be build in the HPC.
