### ISSUE TITLE
PERF: Combine newstack commands which apply transforms.

### ISSUE THREAD

**Issue by blowekamp** [niaid/image_portal_workflows#187]
The following three commands are run:
```
 newstack -x {WORKDIR}/align.xg {WORKDIR}/Source.mrc {WORKDIR}/Align.mrc
 newstack -x {WORKDIR}/stretch.xf {WORKDIR}/aligned.mrc {WORKDIR}/corrected.mrc
 newstack -meansd 150,40 -mo 0 corrected.mrc {BASENAME}.mrc
```

The [newstack command](https://bio3d.colorado.edu/imod/doc/man/newstack.html) can accept multiple `-x/-xform` arguments. These three steps could be combined into
```
newstack -x {WORKDIR}/align.xg -x {WORKDIR}/stretch.xf -meansd 150,40 -mo 0 {WORKDIR}/Source.mrc {WORKDIR}/{BASENAME}.mrc
```

**Comment by philipmac** [comment]
Not understanding this 
assuming input mrc is: `source.mrc` the idea is we replace the above three steps with:

`newstack -x align.xg -x stretch.xf -meansd 150,40 -mo 0 source.mrc out.mrc`

seeing:
`ERROR: NEWSTACK - OPENING OR READING TRANSFORM FILE`

**Comment by philipmac** [comment]
see: https://github.com/niaid/image_portal_workflows/tree/combine_newstack
