### ISSUE TITLE
Write tests for utils.py and refactor tests

### ISSUE THREAD

**Issue by mbopfNIH** [niaid/image_portal_workflows#188]
Learn how to test functions with @task decorator. Put common test fixtures into conftest.py.

**Comment by philipmac** [comment]
use `__wrapped__()` 
eg: https://github.com/niaid/image_portal_workflows/blob/beac57782edd7b4a832d8e973ea01af357a5d085/test/test_callback.py#L29

**Comment by mbopfNIH** [comment]
Added Utils tests. Used __wrapped__ check for `get_input_dir` since that is a `prefect.Task`. Created conftest.py to hold common pytest fixtures. Added dimension constants in `config.py` (e.g. `LARGE_2D`) and commented out unused utils.init_log() function.
