### ISSUE TITLE
Toggle `test_brt` shortcut mode from command line

### ISSUE THREAD

**Issue by mbopfNIH** [niaid/image_portal_workflows#230]
The `test_brt` function can run either with mocked, partially-processed inputs, (shortcut mode) or by running the full `batchruntomo` command. Need to be able to control running either in one or the other mode. Currently it's done by commenting out code, which is error-prone.

**Comment by mbopfNIH** [comment]
Withdrawing this Issue as OBE. We will move away from the shortcut BRT with Prefect 2.

**Comment by philipmac** [comment]
we should no longer be running the mocked outputs I think, it's quicker to generate new outputs with the given BRT params.

**Comment by mbopfNIH** [comment]
Agreed. I was thinking we would pull the `utils.run_brt()` when we move to Prefect 2. Or we could just pull it now and remove the `@pytest.mark.slow` mark.
