### ISSUE TITLE
Run error in QA from 5/26/2023

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#234]
See : https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/dbd7b38a-30af-4963-8d57-61eadf2a3286
The pipeline has been in "running" status since Friday ( for 6 days now)
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/f176fa4e-4108-420a-a95d-cc96162802cf)

**Comment by philipmac** [comment]
copied to dev - runs ok.
https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/9881b5f2-7afd-4e0f-9cc4-46bdc7640aa4?overview
