### ISSUE TITLE
Run error in Prod from 6/2/2023

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#236]
This issue was reported by Bryan H.
"my 2D pipeline jobs keep erroring out."
See pipeline runs:
https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/1ed0ce6e-073c-4df8-be6a-0644de3d951b
https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/a441a7c3-a45d-4edd-8f93-7392c9c7315a
https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/c3516e39-e5cd-4f9a-9286-ec427049bdec

**Comment by philipmac** [comment]
Workflows are functioning normally it appears - API is unavailable. 

Closing.

**Comment by sevaa** [comment]
The bug was on the API side - a wrong enum was used in that place, not AssetType. The error message was misleading.
