### ISSUE TITLE
Formulate the COE list for the Hedwig pipeline

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#241]
Please list the :

![image](https://github.com/niaid/image_portal_workflows/assets/78621685/47ca6add-043f-4879-9193-7a8db32bf1a0)

Please add the dependencies as well.
Please add the version if available, alternately list  "any⁠"

**Comment by NetaFG** [comment]
For more information see ticker: https://github.com/niaid/image_portal_workflows/discussions/242

**Comment by philipmac** [comment]
see: https://github.com/niaid/image_portal_workflows/discussions/242
