### ISSUE TITLE
The 2D pipeline failed in Dev on 6/19/2023

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#247]
See pipeline run:
https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/86b5af51-cc2e-46dd-988b-057860216411

**Comment by philipmac** [comment]
HPC issue post maintenance - modified install doc'd here https://github.com/niaid/image_portal_workflows/pull/248 which should prevent this being possible in future.
