### ISSUE TITLE
Two BRT pipeline runs failed in Dev

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#250]
Pipeline runs:
https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/7cde2e5f-b618-49c4-b856-e6ab8ee13b5e
https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/36df5a5d-709e-4d7c-a3ec-3d6f719f913c
 
Verified with Bryan H. the set of input parameters;
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/c3e0f5cd-c282-4fca-a998-f543d914dee8)

**Comment by philipmac** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/gs1/home/hedwig_dev/dev/lib/python3.10/site-packages/em_workflows/templates/cryo_brt.adoc'

**Comment by philipmac** [comment]
https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/85f72cee-6a7e-4643-a9fe-a4242244fc49
