### ISSUE TITLE
2D pipeline failed in QA - 6/30/2023

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#255]
Pipeline run: https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/4371ffe4-debb-49c9-916d-bf4bf93d8b34
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/3bb47b44-01a5-4049-961e-e47b21f84d7d)

UI:
https://hedwig2qa.niaid.nih.gov/sessions/U2Vzc2lvbjoyMjY3/samples
The sample status did not change to "error" it stayed "Queued".
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/3460dfc2-0636-43eb-a769-16d796062939)

**Comment by philipmac** [comment]
QA is back running again, can be resubmitted.
