### ISSUE TITLE
Pipeline runs are held in "scheduled status" on the Prefect UI - 6/30/2023

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#256]
This was part of the QA testing of the new UI/API release (2.1)
This includes all three pipelines.
See pipeline runs:
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/f8c80a22-7ee3-4717-ad5e-8c047f193128?overview
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/ba6915d0-ec05-497d-a08b-f9552d094494
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/8cdb3ab6-8b08-40da-9bac-46de81d86b71
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/0c7c5192-0c0f-4d0f-90b1-97f05e8d2c34
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/1acb375a-a2cb-45ab-9e87-c285baf902cf
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/7fef411d-ec27-400e-8b74-b6e268cd2f86
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/f486467f-0986-44f0-b93b-c966e7984376
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/8bcf9193-e949-4572-9cb8-fe77ba3a0644
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/4d8565db-4fcf-48c6-a15b-ceb594dace9c
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/44598922-455d-48de-b7fa-c4b405cb3714)

**Comment by philipmac** [comment]
QA has been put back in action, these runs can be resubmitted now.
