### ISSUE TITLE
Code in containers

### ISSUE THREAD

**Issue by annshress** [niaid/image_portal_workflows#275]
Since different developers are working with different operating systems, I think we should consider using docker for development so that two developers will have a same experience.

Example: `bioformats2raw` (an application used for converting .czi files to .zarr) doesn't work with M2 chip, but works on linux.

**Comment by blowekamp** [comment]
I agree having a Docker file to build a reproducible environment would be very useful, and make it easier for developer so set up the correct environment. 

To be a little more specific, `bioformats2raw` works in a linux docker container on with the  "linux/amd64" platform option on the Mac ARMs.

**Comment by mbopfNIH** [comment]
I have `bioformats2raw` running on my M1 chip using Intel-based Python and Java installations via Rosetta. I don't believe the M2 introduced new architecture changes, so the above solution should still work.

**Comment by annshress** [comment]
Yes. It's working in a linux docker container. I am still suggesting that we use Docker for the purpose of reproducible environment.

**Comment by mbopfNIH** [comment]
Yes, I agree that a common Docker dev environment would be helpful. One drawback to doing this could be performance, especially when testing out resource-intensive routines, which `bioformats2raw` can be. So I think it is useful to have the application installed directly on your machine without having to go through Docker. Although, setting up the intel-based environment is a pain.

**Comment by blowekamp** [comment]
It looks like we didn't add the`--max_workers=$nproc` options to bioformats2raw before. That will make that command run nearly nproc-X faster so hopefully the performance difference will be less of an issue.
