### ISSUE TITLE
Some 16bit Tiff files show black after running the 2D pipeline in Prod

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#278]
This issue was reported by Bryan and Cindi on 8/22/2023
Cindi last week ran some 16 bit Tiff images through the 2D pipeline and everything worked fine. She generated some new 16 bit Tiff files yesterday and when running them through the pipeline they are now coming out black again.
Pipeline run:
https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/697b7f1d-3546-45b8-96c0-7fc911df1154
Hedwig link:
https://hedwig.niaid.nih.gov/sessions/U2Vzc2lvbjozMDQ2/samples - the newly ran images are  black while the other images are fine. 
See the attached screenshot:
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/c0c518f6-87e5-48fd-aed5-628b3986e5c9)

**Comment by NetaFG** [comment]
This is the first run they tried to process the new images with:
https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/f890c661-09bd-4aac-9f3f-96cf4abb3181

**Comment by NetaFG** [comment]
According to Bryan: "Cindi last week ran some 16 bit Tiff images through the 2D pipeline and everything worked fine."

This is the run that worked fine.
https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/86c29e83-bfdf-4e7f-89d2-0366d9b81c36
Hedwig UI:
https://hedwig.niaid.nih.gov/sessions/U2Vzc2lvbjozMDM5/samples
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/077408a1-cfc9-4f05-800f-deb41fb8083c)

**Comment by blowekamp** [comment]
One possibility is that the input TIFF only uses the lower 12-bits ( or other lower range), of the 16-bit. I don't believe there is automatic window-level or brightness contrast adjustment for the 2D pipeline. This will require some investigation.

**Comment by blowekamp** [comment]
The current 2d pipeline does 16-bit to 8-bit depth conversion by mapping the range (min/max) from the input to the outputs.

A problematic file named "263K-GO_120_grid2_image.001.tif" was inspected. It has the following statistics:

```
  Minimum: 0
  Maximum: 32767
  Mean: 1481.72
  Sigma: 240.228
  Variance: 57709.3
```
There are 2 pixels with values above 20000, and 51 pixels with values above 5000. These outliers are problematic for the conversion method used, causing a lack of used range of the output image (near black image).

It is recommended to work with the current implementation that the problematic image be preprocessed to remove the outliers then re-uploaded and run through the pipeline again.

**Comment by blowekamp** [comment]
The TIFF files are extracted from a series of images store in a ST(MRC) file that are extracted with the  `mrc2tiff` mod program.

Two preprocessing options were proposed:
 1)  Add options to perform intensity scaling to 8-bit during `mrc2tiff` processing. The following command line option can e used: `-a mn,sd   Scale to mean and SD for conversion to bytes (0,0 for default)`. Where the values of `-a "150,40"` can e used for good visual appearance similar to the default 3DMOD view, and `-a "128,40"` can be used to maximize preserving bright intensities.

2) The IMOD command line tool `ccderaser` an be used to replaces single outlier pixels with interpolated values. A scripted command such as:
   IMOD_OUTPUT_FORMAT=TIF ccderaser -f "$input_filename" "${output_dir}/$(basename $input_filename)"
 Could be used to process each slice. Unfortunately, it appears not be able to process the st file.

3) The `newstack` IMOD command could be used extract 2d mrc files as opposed to tiff files. The pipeline would process these images with EM specific processing including mean/std intensity and anti-aliasing during resampling.

Additional analysis of the spacial location of the outlier pixel was performed. The location was not random and the same pixel was problematic in the whole stack while other frequently repeated. This may indicate a probablatic gain file, or gain correction with the microscope.

**Comment by mbopfNIH** [comment]
Are we sure this is our problem to solve? Where is the line between "bad input data" and "Hedwig-acceptable data"? There might not be a bright-red light delineating the distinction, but I think we should consider it.

**Comment by blowekamp** [comment]
Bryan preprocessed the data with mrc2tiff with the `-a` options and the Hedwig images generation was successful.
