### ISSUE TITLE
create a *small* input to enable czi conversion tests be run in a reasonable length of time

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#289]
current runtimes for tests aren't acceptable.

**Comment by annshress** [comment]
We might need smaller czi files for this?

Or we can skip the `czi to zarr` conversion step entirely (which seems to be taking the long step), and directly use pre-converted zarr files to test the flows (by mocking the czi to zarr steps)

**Comment by blowekamp** [comment]
We may need to contact the microscopist to create a proper CZI file where they have cropped the input image to a small (~1k) size. They hopefully can do this with the same tools they use to create the czi package.

**Comment by mbopfNIH** [comment]
A bit off topic, but is there any chance we could do something similar for BRT and SEM, i.e. make smaller, but valid images for testing? Would be especially useful for GH Actions on PR for running the tests. Currently BRT and SEM are "skipped" based on custom `pytest.mark.slow` and `pytest.mark.local_data` directives.
