### ISSUE TITLE
2D pipeline in Dev is broken

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#301]
See runs:
https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/608a5a65-31ae-498f-80ea-838a07bb6a98
https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/aa48580f-9619-45b7-9dde-56eea303e539

The first run is from an EM session folder and the second run is from an Omics session folder . Both failed.
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/e1b6aefc-4808-4f7e-b4f1-50ae3361e0c1)

Please note that on the Hedwig UI the sample is in the "Queued" Status while on the Prefect UI the sample status is "failed".

**Comment by philipmac** [comment]
there's no expectation that the wf in dev will work in conjunction with the current API at the moment.

**Comment by philipmac** [comment]
Run with updated workflows:
https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/87b737e4-1034-4caf-b62d-e3f5bc31f7d7
