### ISSUE TITLE
ROI pipeline run failed in Dev - 9/15/2023

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#317]
https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/b3e941e9-14c2-446d-b5b5-2232c1136cd6?schematic
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/a6bdc297-a73b-4ef7-a4bf-e00409ac8251)

It seems that Zarr generation failed.

**Comment by annshress** [comment]
https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/f70408d1-8e39-429e-90a0-7c43a42fe9df

Output of the same flow run.

The tentative underlying issue has been reported here: https://github.com/glencoesoftware/bioformats2raw/issues/217

**Comment by NetaFG** [comment]
Re-Tested on 9/20/2023 through the interface and the pipeline run completed successfully.
Test = PASS. 
Pipeline run : https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/8c6ecc1a-0588-4298-b598-688475843935
Hedwig UI: https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjozNTU0/records#N4IgSgpgxg9gTgEwDIEsDOAXFA7A5iALlADUBRMAZQEkB5AOUIEYAaEYgQSQFVTDQ0IAQzhQAFhQxwc+AiBCsADsIjYMFQQFsFAGwgAxFNowQ4hANoguAJj0YoAcQAe2mgCtSATxoARayAC6rMoGRiZoFKIwAO7YhJIArhAAvilAA===
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/8604ecb3-4082-49f3-9376-827852e2b388)

![image](https://github.com/niaid/image_portal_workflows/assets/78621685/b840b131-1fe7-4e38-a40a-40a27b85e69c)
