### ISSUE TITLE
Create new SlurmCluster type

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#321]
BRT does not respond well to being run on >1 process in SlurmCluster

We can add a new SlurmCluster object that can be used by other workflows, that has >1 process available.
We can leave BRT running on the existing config, and import at top of BRT flow as normal. 

Relates to https://github.com/niaid/image_portal_workflows/pull/320

**Comment by annshress** [comment]
This might have been because the memory was being distributed among workers. Now the memory has been greatly increased in size.

**Comment by philipmac** [comment]
closed by https://github.com/niaid/image_portal_workflows/pull/384
