### ISSUE TITLE
update BRT Neuroglancer to new format

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#338]
pytools `visual_min_max` output needs to be massaged to conform to the new metadata format. 

Eg see: 
https://github.com/niaid/image_portal_workflows/blob/f1f6664950a2ffa4d013edc507c56917e1a4f676/docs/source/metadata.yml#L19

**Comment by blowekamp** [comment]
The "visual_min_max" should be marked deprecated. Please replace with `ZarrImage.neuroglancer_shader_parameters`
