### ISSUE TITLE
look at using subflows for big computes

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#355]
from: 
https://docs.prefect.io/2.13.5/concepts/flows/

> When a subflow starts, it will create a new [task runner](https://docs.prefect.io/concepts/task-runners/) for tasks within the subflow. When the subflow completes, the task runner is shut down.

In bioformats2raw single node can get bogged down / run out of memory / behave suboptimally when running many jobs each with high number of threads. 
If we defined a the task runner as a single node, we could could assign high num threads / high ram without consideration of anything else running. (Flow will not demand large number of nodes to run, & nodes will vanish upon completion). Similar to `daskCluster.scale()` but possibly more straight forward.

**Comment by annshress** [comment]
How different is this from the current approach?

**Comment by philipmac** [comment]
see: 
https://docs.prefect.io/2.14.3/concepts/task-runners/#using-multiple-task-runners

**Comment by annshress** [comment]
Added subflows in czi/flow.py on branch `feature/prefect2`; which dedicates a node for single czi file transformation.
