### ISSUE TITLE
Null path in file metadata?

### ISSUE THREAD

**Issue by sevaa** [niaid/image_portal_workflows#367]
Debugging https://jira.niaid.nih.gov/browse/HEDWG2-1063 . The file level metadata for the referenced image goes like this was  either a blank object (`{}`), or an object with null omeXml (`{"omeXml":null}`).

The pipeline run to check was in QA, and the ID on the pipeline run was S9468.

---

Please pass a null/missing **fileMetadata** instead of that. Storing objects with no payload is a waste of storage.

**Comment by philipmac** [comment]
@sevaa  -
We only provide the ome xml file in cases that it contains useful information. 
The ome XML does not currently contain useful information in this workflow it's therefore not provided in this workflow.

So the current response is `..."fileMetadata": {}...`

Please let us know if you'd like us to not provide fileMetadata in some other manner.

**Comment by sevaa** [comment]
That's what my suspicion was. Can you please pass `null` instead, or don't add "fileMetadata" to the enclosing JSON object at all?

**Comment by annshress** [comment]
Hi @sevaa, can you verify these change in `qa` branch?

**Comment by sevaa** [comment]
Not sure how.

**Comment by philipmac** [comment]
@sevaa  - the fix is applied to the QA server, you should be able to retest if you like.

**Comment by sevaa** [comment]
Which pipeline was it?

**Comment by philipmac** [comment]
large 2d conversion 

see: 
{"files": [{"primaryFilePath": "LID/jecohen/maximovao-2023-1102-MTB/RNA-2023-1102-Morphology_Tag-IA_M1_S1-4/Pre_ROI_Images/IA_M2_S1.png", "thumbnailIndex": 0, "title": "IA_M2_S1", "fileMetadata": {"omeXml": null}, "imageSet": [{"imageName": "IA_M2_S1", "imageMetadata": null, "assets": [{"type": "thumbnail", "path": "LID/jecohen/maximovao-2023-1102-MTB/RNA-2023-1102-Morphology_Tag-IA_M1_S1-4/Pre_ROI_Images/IA_M2_S1/IA_M2_S1_sm.jpeg"}, {"type": "keyImage", "path": "LID/jecohen/maximovao-2023-1102-MTB/RNA-2023-1102-Morphology_Tag-IA_M1_S1-4/Pre_ROI_Images/IA_M2_S1/IA_M2_S1_lg.jpeg"}, {"type": "neuroglancerZarr", "path": "LID/jecohen/maximovao-2023-1102-MTB/RNA-2023-1102-Morphology_Tag-IA_M1_S1-4/Pre_ROI_Images/IA_M2_S1/IA_M2_S1.zarr/0", "metadata": {"shader": "RGB", "dimensions": "XY", "shaderParameters": {}}}]}]}, {"primaryFilePath": "LID/jecohen/maximovao-2023-1102-MTB/RNA-2023-1102-Morphology_Tag-IA_M1_S1-4/Pre_ROI_Images/IA_M2_S2.png", "thumbnailIndex": 0, "title": "IA_M2_S2", "fileMetadata": {"omeXml": null}, "imageSet": [{"imageName": "IA_M2_S2", "imageMetadata": null, "assets": [{"type": "thumbnail", "path": "LID/jecohen/maximovao-2023-1102-MTB/RNA-2023-1102-Morphology_Tag-IA_M1_S1-4/Pre_ROI_Images/IA_M2_S2/IA_M2_S2_sm.jpeg"}, {"type": "keyImage", "path": "LID/jecohen/maximovao-2023-1102-MTB/RNA-2023-1102-Morphology_Tag-IA_M1_S1-4/Pre_ROI_Images/IA_M2_S2/IA_M2_S2_lg.jpeg"}, {"type": "neuroglancerZarr", "path": "LID/jecohen/maximovao-2023-1102-MTB/RNA-2023-1102-Morphology_Tag-IA_M1_S1-4/Pre_ROI_Images/IA_M2_S2/IA_M2_S2.zarr/0", "metadata": {"shader": "RGB", "dimensions": "XY", "shaderParameters": {}}}]}]}]}

Note: ` "fileMetadata": {"omeXml": null},` etc

**Comment by sevaa** [comment]
Noted. Although this is not an empty object, that's still the opposite of what I'm asking for - a metadata object with no payload. So not fixed, I presume...

**Comment by sevaa** [comment]
#368 doesn't address the issue. Replacing `{}` with `{"omXml":null}` is not what I was after. Please reopen this issue, or I'll create another.

**Comment by annshress** [comment]
The new response should be as follow,

- If there is not `omeXml`, the response should be `fileMetadata: null`.
- If there is `omeXml`, the response should be `fileMetadata: {"omeXml": "/path/ab/c"}`.

**Comment by sevaa** [comment]
That's what I was after, yes. That's not the current behavior, as seen in QA - I'm getting `{"omeXml": null}` instead.

**Comment by sevaa** [comment]
Retested, this time fileMetadata is null.
