### ISSUE TITLE
One of the Mutlichannell pipeline runs in Prod failed on 12/5/2023

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#396]
Pipeline run :https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/b36dbdc0-5843-4a0b-8ab2-7442f6246bca?overview

**Comment by philipmac** [comment]
workflow had issue removing locks upon finishing. This is an known issue with removing files on HPC, and is not a failure within the callback / perspective of Hedwig.

Re ran job with same inputs to examine if there's something specific with these inputs or a general issue possibly somewhere on HPC, unable to replicate.
