### ISSUE TITLE
Automate Prefect to run tests, nightly, on HPC, as another set of workflows

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#404]
We can create workflow(s) that can be scheduled to run nightly on HPC.
These flows will simply run tests, including large input tests.
This has the additional convenience of not having to move any data around, we can leave a dataset on HPC for these tests.

**Comment by annshress** [comment]
Tests and pushes result as an artifact into prefect server.

Test run: https://prefect2.hedwig-workflow-api.niaiddev.net/flow-runs/flow-run/158b3031-1c89-4bd7-b1b7-c23150a35d4e
Artifact: https://prefect2.hedwig-workflow-api.niaiddev.net/artifacts
