### ISSUE TITLE
One 2D RGB sample file failed the processing of the Irg_2D pipeline in QA on 12/12/2023

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#405]
Pipeline run: https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/a06c3900-50f4-4084-9a62-f9b39d9b7f64
Hedwig interface: https://hedwig2qa.niaid.nih.gov/sessions/U2Vzc2lvbjozMzEy/records
File system: \\ai-fas12.niaid.nih.gov\RMLSOHedwigQA\Projects\RTB\darrellh\kaladik2-2023-1117-Testkeyword\Protein-2023-1117-testtag-Registration_samples\ROI_Images

Sample IA_P2_S2 - failed
All other three samples passed and tested using the Hedwig interface.

**Comment by philipmac** [comment]
see: ("ERROR : convert: no images defined `/gs1/Scratch/hedwig_qa_scratch/tmp2lmx8g0d/IA_P2_S2.tiff' @ error/convert.c/ConvertImageCommand/3235.\n -- ")

suspect input tiff file exceeds allowable input dims for `convert`

**Comment by philipmac** [comment]
debug convert https://gist.github.com/philipmac/555837dc5b5406af61de5e56d8b2223e

**Comment by philipmac** [comment]
Issue with input PNG - user recreated input file and pipeline runs without issue
