### ISSUE TITLE
Prefect 2 testing  -Multichannel run failed in DEV 

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#407]
PIpeline run: https://prefect2.hedwig-workflow-api.niaiddev.net/flow-runs/flow-run/580078f9-cabb-4b43-b492-7875094ed12a
Hedwig UI:https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjozNTcy/samples
File system: \\ai-fas12.niaid.nih.gov\RMLSOHedwigDev\Projects\RTB\darrellh\valekseyev-2023-1012-11\Protein-2023-1018-HQ_Thumbnails-Thumbnails\HQ_Images
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/2be5f236-d9a2-4c5c-a8a2-10a98a6e3cd4)

**Comment by NetaFG** [comment]
I double checked that I've fired the right pipeline:
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/e0df2ad9-e5b0-4790-b23b-c7334820a72c)

**Comment by annshress** [comment]
The pipeline run ( https://prefect2.hedwig-workflow-api.niaiddev.net/flow-runs/flow-run/580078f9-cabb-4b43-b492-7875094ed12a ) above shows the request is coming to the Large 2d PNG pipeline instead.

**Comment by NetaFG** [comment]
Indeed, this is not the correct pipeline for these tyoe of images.

**Comment by philipmac** [comment]
Yeah, wrong pipeline being called.
Closing for now.
