### ISSUE TITLE
always include ALL primary files paths found in input dir

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#415]
Currently if an input file fails to convert it's not listed in the callback.
We should include every input file, even if it fails to convert / run properly.
Ideally we include a reason why it fails. This will have to be a new field in the callback.

**Comment by annshress** [comment]
Should it be discussed with the Backend API who calls the prefect's api?

**Comment by annshress** [comment]
Currently, this behavior is only "expected" with brt runs. Other workflows have the tendency of simply failing/succeeding in a pending state.

**Comment by annshress** [comment]
Added in #423 and #424
