### ISSUE TITLE
BRT pipeline possible refactor: Waiting for all mapped task runs to finish when partially finished tasks could go on with rest of the pipeline

### ISSUE THREAD

**Issue by annshress** [niaid/image_portal_workflows#417]
Shown image shows some of the tasks have already completed, while some are still running. However, completed tasks could pass  their flow runs to next tasks rather than waiting for sister-mapped-tasks to complete

![image](https://github.com/niaid/image_portal_workflows/assets/6479061/363500f4-0c23-4c1a-81af-7ab61807d398)

**Comment by annshress** [comment]
BRT workflow currently fails when handling too many files ( 30 and more .mrc files of size 1G ).

**Comment by philipmac** [comment]
https://prefect2.hedwig-workflow-api.niaiddev.net/task-runs/task-run/a21243dd-e0de-4f2c-9627-c27af7071dd4

then hangs

**Comment by philipmac** [comment]
15:57:06.557 | INFO    | Task run 'gen_ng_metadata-9' - Instantiating HWZarrImages /gs1/Scratch/hedwig_dev_scratch/tmp9z5qokp4/2013-1220-dA30_5-BSC-1_19_rec.zarr
15:57:06.560 | INFO    | Task run 'gen_ng_metadata-9' - Accessing first HWZarrImage
15:57:06.563 | INFO    | Task run 'gen_ng_metadata-9' - Creating ng metadata
15:57:06.563 | INFO    | Task run 'gen_ng_metadata-9' - ... getting shader type
15:57:06.564 | INFO    | Task run 'gen_ng_metadata-9' - ... getting dims
15:57:06.565 | INFO    | Task run 'gen_ng_metadata-9' - ... getting shader params
15:57:06.565 | DEBUG   | pytools.HedwigZarrImage - path: 0/0
15:57:06.567 | INFO    | pytools.utils.histogram - ZARR array needs converting to native byteorder.
...
job-extra': None, 'job-extra-directives': [], 'job-directives-skip': [], 'log-directory': None, 'scheduler-options': {}}}}
15:57:06.570 | INFO    | pytools.HedwigZarrImage - Building histogram for "/gs1/Scratch/hedwig_dev_scratch/tmp9z5qokp4/2013-1220-dA30_5-BSC-1_19_rec.zarr/0"...


job never returns.

concurrency set to 1.

**Comment by annshress** [comment]
This issue has been avoided using enough number of cores for the workflow.

**Comment by annshress** [comment]
Resolved. Test case: https://prefect2.hedwig-workflow-api.niaiddev.net/flow-runs/flow-run/43c12d8e-30a6-4588-b97a-40db2477741a
