### ISSUE TITLE
copy zarr outputs into place in Assets dir

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#446]
Currently not getting copied off temp dir into Assets dir.

**Comment by annshress** [comment]
Noting down for reference:

Assets folder are not removed if they are stale. This means, if the directory exists, the new workflow run will modify the Assets folder with new content, leaving old content if there's no interference. So, in cases of when some outputs are not copied, the old (and maybe wrong) contents might serve as the result.
