### ISSUE TITLE
2D pipeline run crashed in QA

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#459]
See the pipeline run:

https://prefect2.hedwig-workflow-api.niaidqa.net/flow-runs/flow-run/b9f27151-c3be-4474-8b41-f3c5dc6a3ca9
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/c50b83da-2269-422e-8cfb-de2f54fcc661)

More information about the testing can be found in: https://jira.niaid.nih.gov/browse/HEDWG2-1253

**Comment by philipmac** [comment]
large runs triggered AWS Firewall - Firewall rules updated here:

https://github.com/niaid/tf-hedwig-workflow-api/pull/12
