### ISSUE TITLE
The Prefect 2 UI interface run out of  memory after a few minutes

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#462]
Logged into Prefect 2 (dashboard view)
Navigated from the dashboard to a specific run:
https://prefect2.hedwig-workflow-api.niaidqa.net/flow-runs/flow-run/f8259055-3138-4a23-ba52-2544c17913a3

After a few minutes, the UI encountered a run time error.
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/94811c9b-0258-4b6f-86a3-5325798c8a73)

This error repeated itself twice today.

**Comment by philipmac** [comment]
this isn't something we can fix. It's related to the amount of data in these runs, they aren't suitable for viewing graphically.
