### ISSUE TITLE
16 bit Tiffs  are generating black thumbnails

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#466]
Hedwig URL : https://hedwig.niaid.nih.gov/sessions/U2Vzc2lvbjozMTQ0/samples#N4IgygpgzlCWD2A7AMrKAXWiDmIBcoAagKIBKYAkgPIBy+ATADQiECCyAqsfqAIYyxsiCABMw6XgDNJAMVgAbdBABO+ANogO9QgC8AxvXkA3AEYBrAFoAHEwAlS8vfIBCjxDVMAreAA8AsjoAigC8IAC6zFawcooq6hEgUBDyEHpKIgAqAJ5W0PHMSbzKegAW4spYuHggIMxGsBAA7tm5+AAMzEUQMUrKUGAl8I2I+OjKAK4QBfDKmDjivEo8iTPoAMIVvQgj1cj86BxWIosQACIntSuzp7DKqZhI+CCn0HoQiCKVIAC+v99AA==
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/8bb933ab-b5db-417a-87ca-f8b7992512ab)

Please note that the 2D pipeline was updated formerly to support 16 bit files therefore these files should have 
A sample 16 bit files can be found in the Hedwig Teams channel: https://nih.sharepoint.com/:f:/r/sites/NIAID-NCATSCollaboration/Shared%20Documents/Hedwig%20V2/Sample%2016bit%20Files?csf=1&web=1&e=JO3RWJ

**Comment by NetaFG** [comment]
Pipeline run : http://prefect2.hedwig-workflow-api.niaidprod.net/flow-runs/flow-run/b5da08a8-f8bb-4916-8765-fbf75eea4cdc
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/29ab9bce-273c-4cb4-911b-0d28bbb29f31)

**Comment by NetaFG** [comment]
Please find attached a sample image showing how the thumbnails should look:

![image](https://github.com/niaid/image_portal_workflows/assets/78621685/b3c80415-9b4a-436b-ace4-256ab35fecfd)

**Comment by NetaFG** [comment]
File path: 
: \\ai-fas12.niaid.nih.gov\RMLEMHedwigProd\Projects\RTB\efischer\hansenbry-2024-0117-DMID\TEM-2024-0118-VLP-quant

**Comment by blowekamp** [comment]
The images come from a new microscope and with new tools which export the images to 16-bit TIFFs.

The tiff contains outlier pixel ( perhaps caused by X-rays ) for example 1632 value with a median of the image at 151. The range preserving approach of pytools.convert will not work with this.

A similar issue was previous encountered with 16-bit tiff exported from FIBSEM images. For this the 16-bit were preserved I the OME ZARR, but the intensity was windows with a MAD algorithm when viewing.

**Comment by blowekamp** [comment]
The command line from `[convert_3d_mrc_to_tiff](https://github.com/niaid/image_portal_workflows/blob/ea5d4d6a96953e282d0cf7537a02811626664d23/em_workflows/dm_conversion/flow.py#L70)` was run on 4 sample input 16-bit tiff files. The conversion looked good. And Bryan said "those look good to me". This can address this issue.

However, it raises the question if these 16-bit TIFF need to be processed with this separate conversion, or if all can be run through the IMOD newstack command.
