### ISSUE TITLE
All QA pipeline runs failed on 5/22/2024.

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#472]
https://prefect2.hedwig-workflow-api.niaidqa.net/dashboard

![image](https://github.com/niaid/image_portal_workflows/assets/78621685/603cff24-f7e2-4d16-a885-779cb750d2f7)

**Comment by philipmac** [comment]
QA experienced issues during updates during HPC outage. 
Should be resolved now. All runs are either completed, or running correctly ATM.
![image](https://github.com/niaid/image_portal_workflows/assets/1271929/6e420a2f-87d5-47d0-abe0-6427488772dd)
